- name: create backend directory
  become: yes
  file:
    path: ~/backend
    state: directory
    mode: 0755
- name: copy backend files
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend/artifact.tar.gz
- name: unpack backend files
  become: yes
  shell: |
    cd ~/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz
- name: start app 
  become: yes
  shell: |
    cd ~/backend
    sudo yum install -y gcc-c++ make 
    curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -     
    sudo yum install -y nodejs 
    npm -v     
    npm install
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env
